'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by coded UI test builder.
'      Version: 12.0.0.0
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.HtmlControls
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace Reference.John.CodedUI.Fixture
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''SimpleGoogleSearch for stack demo
        '''</summary>
        Public Sub SimpleGoogleSearch()
            Dim uIRunningapplicationsWindow As WinWindow = Me.UIRunningapplicationsWindow.UIRunningapplicationsClient.UIRunningapplicationsWindow
            Dim uIItemWindow As WinWindow = Me.UILoginWindowsInternetWindow.UIAddressBarClient.UIItemWindow
            Dim uIUsernameEdit As HtmlEdit = Me.UILoginWindowsInternetWindow.UILoginDocument.UIUsernameEdit
            Dim uIQEdit As HtmlEdit = Me.UILoginWindowsInternetWindow.UIGoogleDocument.UIQEdit
            Dim uIIresPane As HtmlDiv = Me.UILoginWindowsInternetWindow.UIGoogleDocument.UIIresPane
            Dim uICenter_colPane As HtmlDiv = Me.UILoginWindowsInternetWindow.UIGoogleDocument.UICenter_colPane
            Dim uICreateeasytomaintainPane As HtmlDiv = Me.UILoginWindowsInternetWindow.UIGoogleDocument.UITadsPane.UICreateeasytomaintainPane

            'Click 'Running applications' window
            Mouse.Click(uIRunningapplicationsWindow, New Point(33, 16))

            'Click window
            Mouse.Click(uIItemWindow, New Point(84, 8))

            'Type 'www.google{Down}{Enter}' in 'Username:' text box
            Keyboard.SendKeys(uIUsernameEdit, Me.SimpleGoogleSearchParams.UIUsernameEditSendKeys, ModifierKeys.None)

            'Type 'coded ui' in 'q' text box
            uIQEdit.Text = Me.SimpleGoogleSearchParams.UIQEditText

            'Type ' ' in 'q' text box
            Keyboard.SendKeys(uIQEdit, Me.SimpleGoogleSearchParams.UIQEditSendKeys, ModifierKeys.None)

            'Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true

            'Mouse hover 'ires' pane at (1, 1)
            Mouse.Hover(uIIresPane, New Point(1, 1))

            'Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false

            'Type 'coded uite' in 'q' text box
            uIQEdit.Text = Me.SimpleGoogleSearchParams.UIQEditText1

            'Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true

            'Mouse hover 'center_col' pane at (1, 1)
            Mouse.Hover(uICenter_colPane, New Point(1, 1))

            'Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false

            'Type 'coded ui t' in 'q' text box
            uIQEdit.Text = Me.SimpleGoogleSearchParams.UIQEditText2

            'Type 'est' in 'q' text box
            Keyboard.SendKeys(uIQEdit, Me.SimpleGoogleSearchParams.UIQEditSendKeys1, ModifierKeys.None)

            'Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true

            'Mouse hover 'Create easy to maintain tests with Visua' pane at (1, 1)
            Mouse.Hover(uICreateeasytomaintainPane, New Point(1, 1))

            'Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false

            'Type 'coded ui testing' in 'q' text box
            uIQEdit.Text = Me.SimpleGoogleSearchParams.UIQEditText3

            'Type '{Enter}' in 'q' text box
            Keyboard.SendKeys(uIQEdit, Me.SimpleGoogleSearchParams.UIQEditSendKeys2, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''AssertGoogleSectionExists - Use 'AssertGoogleSectionExistsExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub AssertGoogleSectionExists()
            Dim uIHdtbSumPane As HtmlDiv = Me.UILoginWindowsInternetWindow.UICodeduitestingGoogleDocument.UIHdtbSumPane

            'Verify that the 'Id' property of 'hdtbSum' pane equals 'hdtbSum'
            Assert.AreEqual(Me.AssertGoogleSectionExistsExpectedValues.UIHdtbSumPaneId, uIHdtbSumPane.Id, "Same value for id.")
        End Sub
        
        '''<summary>
        '''SecondGoogleTry - Use 'SecondGoogleTryParams' to pass parameters into this method.
        '''</summary>
        Public Sub SecondGoogleTry()
            Dim uIItemWindow As WinWindow = Me.UILoginWindowsInternetWindow.UIAddressBarClient.UIItemWindow
            Dim uIUsernameEdit As HtmlEdit = Me.UILoginWindowsInternetWindow.UILoginDocument.UIUsernameEdit
            Dim uIQEdit As HtmlEdit = Me.UILoginWindowsInternetWindow.UIGoogleDocument.UIQEdit

            'Go to web page 'https://home.compaid.com/' using new browser instance
            Me.UILoginWindowsInternetWindow.LaunchUrl(New System.Uri(Me.SecondGoogleTryParams.UILoginWindowsInternetWindowUrl))

            'Click window
            Mouse.Click(uIItemWindow, New Point(55, 10))

            'Type 'www.google.com{Enter}' in 'Username:' text box
            Keyboard.SendKeys(uIUsernameEdit, Me.SecondGoogleTryParams.UIUsernameEditSendKeys, ModifierKeys.None)

            'Type 'coded ui test' in 'q' text box
            uIQEdit.Text = Me.SecondGoogleTryParams.UIQEditText

            'Type '{Enter}' in 'q' text box
            Keyboard.SendKeys(uIQEdit, Me.SecondGoogleTryParams.UIQEditSendKeys, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''TestSearchTextBox - Use 'TestSearchTextBoxExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub TestSearchTextBox()
            Dim uIQEdit As HtmlEdit = Me.UILoginWindowsInternetWindow.UIGoogleDocument.UIQEdit

            'Verify that the 'ControlType' property of 'q' text box equals 'Edit'
            Assert.AreEqual(Me.TestSearchTextBoxExpectedValues.UIQEditControlType, uIQEdit.ControlType.ToString, "coded ui test")
        End Sub
        
        '''<summary>
        '''TestChromeSearchBox - Use 'TestChromeSearchBoxParams' to pass parameters into this method.
        '''</summary>
        Public Sub TestChromeSearchBox()
            Dim uIAddressandsearchbarEdit As WinEdit = Me.UIChromeGoogleChromeWindow.UIAddressandsearchbarGroup.UIAddressandsearchbarEdit

            'Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
            Dim uIChromeGoogleChromeWindow As ApplicationUnderTest = ApplicationUnderTest.Launch(Me.TestChromeSearchBoxParams.UIChromeGoogleChromeWindowExePath, Me.TestChromeSearchBoxParams.UIChromeGoogleChromeWindowAlternateExePath)

            'Click 'Address and search bar' text box
            Mouse.Click(uIAddressandsearchbarEdit, New Point(431, 20))

            'Type 'www.google.com{Enter}coded{Back}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, Me.TestChromeSearchBoxParams.UIAddressandsearchbarEditSendKeys, ModifierKeys.None)

            'Type ' ui test{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, Me.TestChromeSearchBoxParams.UIAddressandsearchbarEditSendKeys1, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''TestAddressBox - Use 'TestAddressBoxExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub TestAddressBox()
            Dim uIAddressandsearchbarEdit As WinEdit = Me.UIChromeGoogleChromeWindow.UIAddressandsearchbarGroup.UIAddressandsearchbarEdit

            'Verify that the 'ControlType' property of 'Address and search bar' text box equals 'Edit'
            Assert.AreEqual(Me.TestAddressBoxExpectedValues.UIAddressandsearchbarEditControlType, uIAddressandsearchbarEdit.ControlType.ToString)
        End Sub
        
        '''<summary>
        '''RecordedMethodControlSelection - Use 'RecordedMethodControlSelectionParams' to pass parameters into this method.
        '''</summary>
        Public Sub RecordedMethodControlSelection()
            Dim uIAddressandsearchbarEdit As WinEdit = Me.UIChromeGoogleChromeWindow.UIAddressandsearchbarGroup.UIAddressandsearchbarEdit

            'Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
            Dim uIChromeGoogleChromeWindow As ApplicationUnderTest = ApplicationUnderTest.Launch(Me.RecordedMethodControlSelectionParams.UIChromeGoogleChromeWindowExePath, Me.RecordedMethodControlSelectionParams.UIChromeGoogleChromeWindowAlternateExePath)

            'Type '********' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, Me.RecordedMethodControlSelectionParams.UIAddressandsearchbarEditSendKeys, true)
        End Sub
        
        '''<summary>
        '''htmlwthreecontrols - Use 'htmlwthreecontrolsParams' to pass parameters into this method.
        '''</summary>
        Public Sub htmlwthreecontrols()
            Dim uIDesktopClient As WinClient = Me.UIItemWindow.UIItemWindow1.UIDesktopClient
            Dim uIAddressandsearchbarEdit As WinEdit = Me.UINewTabGoogleChromeWindow.UIAddressandsearchbarGroup.UIAddressandsearchbarEdit
            Dim uIChromeLegacyWindowClient As WinClient = Me.UINewTabGoogleChromeWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient

            'Click 'Desktop' client
            Mouse.Click(uIDesktopClient, New Point(0, 39))

            'Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
            Dim uINewTabGoogleChromeWindow As ApplicationUnderTest = ApplicationUnderTest.Launch(Me.htmlwthreecontrolsParams.UINewTabGoogleChromeWindowExePath, Me.htmlwthreecontrolsParams.UINewTabGoogleChromeWindowAlternateExePath)

            'Type '********' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, Me.htmlwthreecontrolsParams.UIAddressandsearchbarEditSendKeys, ModifierKeys.Control, true)

            'Type '{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, Me.htmlwthreecontrolsParams.UIAddressandsearchbarEditSendKeys1, ModifierKeys.None)

            'Move 'Chrome Legacy Window' client
            Mouse.StartDragging(uIChromeLegacyWindowClient, New Point(1104, 78))
            Mouse.StopDragging(uIChromeLegacyWindowClient, -6, 111)
        End Sub
        
        '''<summary>
        '''Testthree - Use 'TestthreeParams' to pass parameters into this method.
        '''</summary>
        Public Sub Testthree()
            Dim uIAddressandsearchbarEdit As WinEdit = Me.UINewTabGoogleChromeWindow.UIAddressandsearchbarGroup.UIAddressandsearchbarEdit

            'Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
            Dim uINewTabGoogleChromeWindow As ApplicationUnderTest = ApplicationUnderTest.Launch(Me.TestthreeParams.UINewTabGoogleChromeWindowExePath, Me.TestthreeParams.UINewTabGoogleChromeWindowAlternateExePath)

            'Type '********' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, Me.TestthreeParams.UIAddressandsearchbarEditSendKeys, ModifierKeys.Control, true)

            'Type '{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, Me.TestthreeParams.UIAddressandsearchbarEditSendKeys1, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''daf - Use 'dafParams' to pass parameters into this method.
        '''</summary>
        Public Sub daf()
            Dim uIItemWindow As WinWindow = Me.UILoginWindowsInternetWindow.UIItemWindow.UIItemClient.UIItemWindow
            Dim uIItemWindow1 As WinWindow = Me.UILoginWindowsInternetWindow.UIAddressBarClient.UIItemWindow
            Dim uIUsernameEdit As HtmlEdit = Me.UILoginWindowsInternetWindow.UILoginDocument.UIUsernameEdit

            'Go to web page 'https://home.compaid.com/' using new browser instance
            Me.UILoginWindowsInternetWindow.LaunchUrl(New System.Uri(Me.dafParams.UILoginWindowsInternetWindowUrl))

            'Double-Click window
            Mouse.DoubleClick(uIItemWindow, New Point(313, 8))

            'The control is not available or not valid.

            'Click window
            Mouse.Click(uIItemWindow1, New Point(214, 9))

            'Type 'Control + v' in 'Username:' text box
            Keyboard.SendKeys(uIUsernameEdit, Me.dafParams.UIUsernameEditSendKeys, ModifierKeys.Control)

            'Type '{Enter}' in 'Username:' text box
            Keyboard.SendKeys(uIUsernameEdit, Me.dafParams.UIUsernameEditSendKeys1, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''dafdfadsf - Use 'dafdfadsfParams' to pass parameters into this method.
        '''</summary>
        Public Sub dafdfadsf()
            Dim uIRunningapplicationsWindow As WinWindow = Me.UIRunningapplicationsWindow.UIRunningapplicationsClient.UIRunningapplicationsWindow
            Dim uIItemWindow1 As WinWindow = Me.UILoginWindowsInternetWindow.UIAddressBarClient.UIItemWindow1
            Dim uIItemWindow As WinWindow = Me.UILoginWindowsInternetWindow.UIAddressBarClient.UIItemWindow
            Dim uILastnameEdit As HtmlEdit = Me.UILoginWindowsInternetWindow.UIHTMLFormsandInputDocument.UILastnameEdit

            'Click 'Running applications' window
            Mouse.Click(uIRunningapplicationsWindow, New Point(58, 17))

            'Click window
            Mouse.Click(uIItemWindow1, New Point(302, 5))

            'Click window
            Mouse.Click(uIItemWindow, New Point(302, 5))

            'Type '{Enter}' in 'lastname' text box
            Keyboard.SendKeys(uILastnameEdit, Me.dafdfadsfParams.UILastnameEditSendKeys, ModifierKeys.None)
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property SimpleGoogleSearchParams() As SimpleGoogleSearchParams
            Get
                If (Me.mSimpleGoogleSearchParams Is Nothing) Then
                    Me.mSimpleGoogleSearchParams = New SimpleGoogleSearchParams()
                End If
                Return Me.mSimpleGoogleSearchParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property AssertGoogleSectionExistsExpectedValues() As AssertGoogleSectionExistsExpectedValues
            Get
                If (Me.mAssertGoogleSectionExistsExpectedValues Is Nothing) Then
                    Me.mAssertGoogleSectionExistsExpectedValues = New AssertGoogleSectionExistsExpectedValues()
                End If
                Return Me.mAssertGoogleSectionExistsExpectedValues
            End Get
        End Property
        
        Public Overridable ReadOnly Property SecondGoogleTryParams() As SecondGoogleTryParams
            Get
                If (Me.mSecondGoogleTryParams Is Nothing) Then
                    Me.mSecondGoogleTryParams = New SecondGoogleTryParams()
                End If
                Return Me.mSecondGoogleTryParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property TestSearchTextBoxExpectedValues() As TestSearchTextBoxExpectedValues
            Get
                If (Me.mTestSearchTextBoxExpectedValues Is Nothing) Then
                    Me.mTestSearchTextBoxExpectedValues = New TestSearchTextBoxExpectedValues()
                End If
                Return Me.mTestSearchTextBoxExpectedValues
            End Get
        End Property
        
        Public Overridable ReadOnly Property TestChromeSearchBoxParams() As TestChromeSearchBoxParams
            Get
                If (Me.mTestChromeSearchBoxParams Is Nothing) Then
                    Me.mTestChromeSearchBoxParams = New TestChromeSearchBoxParams()
                End If
                Return Me.mTestChromeSearchBoxParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property TestAddressBoxExpectedValues() As TestAddressBoxExpectedValues
            Get
                If (Me.mTestAddressBoxExpectedValues Is Nothing) Then
                    Me.mTestAddressBoxExpectedValues = New TestAddressBoxExpectedValues()
                End If
                Return Me.mTestAddressBoxExpectedValues
            End Get
        End Property
        
        Public Overridable ReadOnly Property RecordedMethodControlSelectionParams() As RecordedMethodControlSelectionParams
            Get
                If (Me.mRecordedMethodControlSelectionParams Is Nothing) Then
                    Me.mRecordedMethodControlSelectionParams = New RecordedMethodControlSelectionParams()
                End If
                Return Me.mRecordedMethodControlSelectionParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property htmlwthreecontrolsParams() As htmlwthreecontrolsParams
            Get
                If (Me.mhtmlwthreecontrolsParams Is Nothing) Then
                    Me.mhtmlwthreecontrolsParams = New htmlwthreecontrolsParams()
                End If
                Return Me.mhtmlwthreecontrolsParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property TestthreeParams() As TestthreeParams
            Get
                If (Me.mTestthreeParams Is Nothing) Then
                    Me.mTestthreeParams = New TestthreeParams()
                End If
                Return Me.mTestthreeParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property dafParams() As dafParams
            Get
                If (Me.mdafParams Is Nothing) Then
                    Me.mdafParams = New dafParams()
                End If
                Return Me.mdafParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property dafdfadsfParams() As dafdfadsfParams
            Get
                If (Me.mdafdfadsfParams Is Nothing) Then
                    Me.mdafdfadsfParams = New dafdfadsfParams()
                End If
                Return Me.mdafdfadsfParams
            End Get
        End Property
        
        Public ReadOnly Property UIRunningapplicationsWindow() As UIRunningapplicationsWindow
            Get
                If (Me.mUIRunningapplicationsWindow Is Nothing) Then
                    Me.mUIRunningapplicationsWindow = New UIRunningapplicationsWindow()
                End If
                Return Me.mUIRunningapplicationsWindow
            End Get
        End Property
        
        Public ReadOnly Property UILoginWindowsInternetWindow() As UILoginWindowsInternetWindow
            Get
                If (Me.mUILoginWindowsInternetWindow Is Nothing) Then
                    Me.mUILoginWindowsInternetWindow = New UILoginWindowsInternetWindow()
                End If
                Return Me.mUILoginWindowsInternetWindow
            End Get
        End Property
        
        Public ReadOnly Property UIChromeGoogleChromeWindow() As UIChromeGoogleChromeWindow
            Get
                If (Me.mUIChromeGoogleChromeWindow Is Nothing) Then
                    Me.mUIChromeGoogleChromeWindow = New UIChromeGoogleChromeWindow()
                End If
                Return Me.mUIChromeGoogleChromeWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow2
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow2()
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        
        Public ReadOnly Property UINewTabGoogleChromeWindow() As UINewTabGoogleChromeWindow
            Get
                If (Me.mUINewTabGoogleChromeWindow Is Nothing) Then
                    Me.mUINewTabGoogleChromeWindow = New UINewTabGoogleChromeWindow()
                End If
                Return Me.mUINewTabGoogleChromeWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mSimpleGoogleSearchParams As SimpleGoogleSearchParams
        
        Private mAssertGoogleSectionExistsExpectedValues As AssertGoogleSectionExistsExpectedValues
        
        Private mSecondGoogleTryParams As SecondGoogleTryParams
        
        Private mTestSearchTextBoxExpectedValues As TestSearchTextBoxExpectedValues
        
        Private mTestChromeSearchBoxParams As TestChromeSearchBoxParams
        
        Private mTestAddressBoxExpectedValues As TestAddressBoxExpectedValues
        
        Private mRecordedMethodControlSelectionParams As RecordedMethodControlSelectionParams
        
        Private mhtmlwthreecontrolsParams As htmlwthreecontrolsParams
        
        Private mTestthreeParams As TestthreeParams
        
        Private mdafParams As dafParams
        
        Private mdafdfadsfParams As dafdfadsfParams
        
        Private mUIRunningapplicationsWindow As UIRunningapplicationsWindow
        
        Private mUILoginWindowsInternetWindow As UILoginWindowsInternetWindow
        
        Private mUIChromeGoogleChromeWindow As UIChromeGoogleChromeWindow
        
        Private mUIItemWindow As UIItemWindow2
        
        Private mUINewTabGoogleChromeWindow As UINewTabGoogleChromeWindow
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'SimpleGoogleSearch'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class SimpleGoogleSearchParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'www.google{Down}{Enter}' in 'Username:' text box
        '''</summary>
        Public UIUsernameEditSendKeys As String = "www.google{Down}{Enter}"
        
        '''<summary>
        '''Type 'coded ui' in 'q' text box
        '''</summary>
        Public UIQEditText As String = "coded ui"
        
        '''<summary>
        '''Type ' ' in 'q' text box
        '''</summary>
        Public UIQEditSendKeys As String = " "
        
        '''<summary>
        '''Type 'coded uite' in 'q' text box
        '''</summary>
        Public UIQEditText1 As String = "coded uite"
        
        '''<summary>
        '''Type 'coded ui t' in 'q' text box
        '''</summary>
        Public UIQEditText2 As String = "coded ui t"
        
        '''<summary>
        '''Type 'est' in 'q' text box
        '''</summary>
        Public UIQEditSendKeys1 As String = "est"
        
        '''<summary>
        '''Type 'coded ui testing' in 'q' text box
        '''</summary>
        Public UIQEditText3 As String = "coded ui testing"
        
        '''<summary>
        '''Type '{Enter}' in 'q' text box
        '''</summary>
        Public UIQEditSendKeys2 As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'AssertGoogleSectionExists'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class AssertGoogleSectionExistsExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that the 'Id' property of 'hdtbSum' pane equals 'hdtbSum'
        '''</summary>
        Public UIHdtbSumPaneId As String = "hdtbSum"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'SecondGoogleTry'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class SecondGoogleTryParams
        
        #Region "Fields"
        '''<summary>
        '''Go to web page 'https://home.compaid.com/' using new browser instance
        '''</summary>
        Public UILoginWindowsInternetWindowUrl As String = "https://home.compaid.com/"
        
        '''<summary>
        '''Type 'www.google.com{Enter}' in 'Username:' text box
        '''</summary>
        Public UIUsernameEditSendKeys As String = "www.google.com{Enter}"
        
        '''<summary>
        '''Type 'coded ui test' in 'q' text box
        '''</summary>
        Public UIQEditText As String = "coded ui test"
        
        '''<summary>
        '''Type '{Enter}' in 'q' text box
        '''</summary>
        Public UIQEditSendKeys As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'TestSearchTextBox'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class TestSearchTextBoxExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that the 'ControlType' property of 'q' text box equals 'Edit'
        '''</summary>
        Public UIQEditControlType As String = "Edit"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'TestChromeSearchBox'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class TestChromeSearchBoxParams
        
        #Region "Fields"
        '''<summary>
        '''Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
        '''</summary>
        Public UIChromeGoogleChromeWindowExePath As String = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
        
        '''<summary>
        '''Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
        '''</summary>
        Public UIChromeGoogleChromeWindowAlternateExePath As String = "%ProgramFiles%\Google\Chrome\Application\chrome.exe"
        
        '''<summary>
        '''Type 'www.google.com{Enter}coded{Back}' in 'Address and search bar' text box
        '''</summary>
        Public UIAddressandsearchbarEditSendKeys As String = "www.google.com{Enter}coded{Back}"
        
        '''<summary>
        '''Type ' ui test{Enter}' in 'Address and search bar' text box
        '''</summary>
        Public UIAddressandsearchbarEditSendKeys1 As String = " ui test{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'TestAddressBox'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class TestAddressBoxExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that the 'ControlType' property of 'Address and search bar' text box equals 'Edit'
        '''</summary>
        Public UIAddressandsearchbarEditControlType As String = "Edit"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'RecordedMethodControlSelection'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class RecordedMethodControlSelectionParams
        
        #Region "Fields"
        '''<summary>
        '''Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
        '''</summary>
        Public UIChromeGoogleChromeWindowExePath As String = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
        
        '''<summary>
        '''Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
        '''</summary>
        Public UIChromeGoogleChromeWindowAlternateExePath As String = "%ProgramFiles%\Google\Chrome\Application\chrome.exe"
        
        '''<summary>
        '''Type '********' in 'Address and search bar' text box
        '''</summary>
        Public UIAddressandsearchbarEditSendKeys As String = "p3bIhP9zf6b9zkmGTIJO9Ns/JehB4dQdxZm5GL55EE/T0OgREXveO0t3ieDJZSphUgue3wWIFaQ="
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'htmlwthreecontrols'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class htmlwthreecontrolsParams
        
        #Region "Fields"
        '''<summary>
        '''Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
        '''</summary>
        Public UINewTabGoogleChromeWindowExePath As String = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
        
        '''<summary>
        '''Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
        '''</summary>
        Public UINewTabGoogleChromeWindowAlternateExePath As String = "%ProgramFiles%\Google\Chrome\Application\chrome.exe"
        
        '''<summary>
        '''Type '********' in 'Address and search bar' text box
        '''</summary>
        Public UIAddressandsearchbarEditSendKeys As String = "uAC2C/piouHi8hWw0aYkUg=="
        
        '''<summary>
        '''Type '{Enter}' in 'Address and search bar' text box
        '''</summary>
        Public UIAddressandsearchbarEditSendKeys1 As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'Testthree'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class TestthreeParams
        
        #Region "Fields"
        '''<summary>
        '''Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
        '''</summary>
        Public UINewTabGoogleChromeWindowExePath As String = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
        
        '''<summary>
        '''Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
        '''</summary>
        Public UINewTabGoogleChromeWindowAlternateExePath As String = "%ProgramFiles%\Google\Chrome\Application\chrome.exe"
        
        '''<summary>
        '''Type '********' in 'Address and search bar' text box
        '''</summary>
        Public UIAddressandsearchbarEditSendKeys As String = "uAC2C/piouHi8hWw0aYkUg=="
        
        '''<summary>
        '''Type '{Enter}' in 'Address and search bar' text box
        '''</summary>
        Public UIAddressandsearchbarEditSendKeys1 As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'daf'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class dafParams
        
        #Region "Fields"
        '''<summary>
        '''Go to web page 'https://home.compaid.com/' using new browser instance
        '''</summary>
        Public UILoginWindowsInternetWindowUrl As String = "https://home.compaid.com/"
        
        '''<summary>
        '''Type 'Control + v' in 'Username:' text box
        '''</summary>
        Public UIUsernameEditSendKeys As String = "v"
        
        '''<summary>
        '''Type '{Enter}' in 'Username:' text box
        '''</summary>
        Public UIUsernameEditSendKeys1 As String = "{Enter}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'dafdfadsf'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class dafdfadsfParams
        
        #Region "Fields"
        '''<summary>
        '''Type '{Enter}' in 'lastname' text box
        '''</summary>
        Public UILastnameEditSendKeys As String = "{Enter}"
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIRunningapplicationsWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Running applications"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "MSTaskSwWClass"
            Me.WindowTitles.Add("Running applications")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIRunningapplicationsClient() As UIRunningapplicationsClient
            Get
                If (Me.mUIRunningapplicationsClient Is Nothing) Then
                    Me.mUIRunningapplicationsClient = New UIRunningapplicationsClient(Me)
                End If
                Return Me.mUIRunningapplicationsClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIRunningapplicationsClient As UIRunningapplicationsClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIRunningapplicationsClient
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinControl.PropertyNames.Name) = "Running applications"
            Me.WindowTitles.Add("Running applications")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIRunningapplicationsWindow() As WinWindow
            Get
                If (Me.mUIRunningapplicationsWindow Is Nothing) Then
                    Me.mUIRunningapplicationsWindow = New WinWindow(Me)
                    Me.mUIRunningapplicationsWindow.SearchProperties(WinWindow.PropertyNames.Name) = "Running applications"
                    Me.mUIRunningapplicationsWindow.SearchProperties(WinWindow.PropertyNames.ClassName) = "MSTaskListWClass"
                    Me.mUIRunningapplicationsWindow.WindowTitles.Add("Running applications")
                End If
                Return Me.mUIRunningapplicationsWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIRunningapplicationsWindow As WinWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UILoginWindowsInternetWindow
        Inherits BrowserWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(UITestControl.PropertyNames.Name) = "Login"
            Me.SearchProperties(UITestControl.PropertyNames.ClassName) = "IEFrame"
            Me.WindowTitles.Add("Login")
            Me.WindowTitles.Add("Google")
            Me.WindowTitles.Add("coded ui testing - Google Search")
            Me.WindowTitles.Add("https://home.compaid.com/")
            Me.WindowTitles.Add("HTML Forms and Input")
        End Sub
        
        Public Sub LaunchUrl(ByVal url As System.Uri)
            Me.CopyFrom(BrowserWindow.Launch(url))
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAddressBarClient() As UIAddressBarClient
            Get
                If (Me.mUIAddressBarClient Is Nothing) Then
                    Me.mUIAddressBarClient = New UIAddressBarClient(Me)
                End If
                Return Me.mUIAddressBarClient
            End Get
        End Property
        
        Public ReadOnly Property UILoginDocument() As UILoginDocument
            Get
                If (Me.mUILoginDocument Is Nothing) Then
                    Me.mUILoginDocument = New UILoginDocument(Me)
                End If
                Return Me.mUILoginDocument
            End Get
        End Property
        
        Public ReadOnly Property UIGoogleDocument() As UIGoogleDocument
            Get
                If (Me.mUIGoogleDocument Is Nothing) Then
                    Me.mUIGoogleDocument = New UIGoogleDocument(Me)
                End If
                Return Me.mUIGoogleDocument
            End Get
        End Property
        
        Public ReadOnly Property UICodeduitestingGoogleDocument() As UICodeduitestingGoogleDocument
            Get
                If (Me.mUICodeduitestingGoogleDocument Is Nothing) Then
                    Me.mUICodeduitestingGoogleDocument = New UICodeduitestingGoogleDocument(Me)
                End If
                Return Me.mUICodeduitestingGoogleDocument
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow(Me)
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        
        Public ReadOnly Property UIHTMLFormsandInputDocument() As UIHTMLFormsandInputDocument
            Get
                If (Me.mUIHTMLFormsandInputDocument Is Nothing) Then
                    Me.mUIHTMLFormsandInputDocument = New UIHTMLFormsandInputDocument(Me)
                End If
                Return Me.mUIHTMLFormsandInputDocument
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAddressBarClient As UIAddressBarClient
        
        Private mUILoginDocument As UILoginDocument
        
        Private mUIGoogleDocument As UIGoogleDocument
        
        Private mUICodeduitestingGoogleDocument As UICodeduitestingGoogleDocument
        
        Private mUIItemWindow As UIItemWindow
        
        Private mUIHTMLFormsandInputDocument As UIHTMLFormsandInputDocument
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIAddressBarClient
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinControl.PropertyNames.Name) = "Address Bar"
            Me.WindowTitles.Add("Login")
            Me.WindowTitles.Add("HTML Forms and Input")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemWindow() As WinWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New WinWindow(Me)
                    Me.mUIItemWindow.SearchProperties(WinWindow.PropertyNames.ClassName) = "Edit"
                    Me.mUIItemWindow.WindowTitles.Add("Login")
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow1() As WinWindow
            Get
                If (Me.mUIItemWindow1 Is Nothing) Then
                    Me.mUIItemWindow1 = New WinWindow(Me)
                    Me.mUIItemWindow1.SearchProperties(WinWindow.PropertyNames.ClassName) = "AddressDisplay Control"
                    Me.mUIItemWindow1.WindowTitles.Add("HTML Forms and Input")
                End If
                Return Me.mUIItemWindow1
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemWindow As WinWindow
        
        Private mUIItemWindow1 As WinWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UILoginDocument
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = "Body"
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "False"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = "Login"
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "https://home.compaid.com/"
            Me.WindowTitles.Add("Login")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIUsernameEdit() As HtmlEdit
            Get
                If (Me.mUIUsernameEdit Is Nothing) Then
                    Me.mUIUsernameEdit = New HtmlEdit(Me)
                    Me.mUIUsernameEdit.SearchProperties(HtmlEdit.PropertyNames.Id) = "dnn_ctr635_Login_Login_ActiveDirectory_txtUsername"
                    Me.mUIUsernameEdit.SearchProperties(HtmlEdit.PropertyNames.Name) = "dnn$ctr635$Login$Login_ActiveDirectory$txtUsername"
                    Me.mUIUsernameEdit.FilterProperties(HtmlEdit.PropertyNames.LabeledBy) = "Username:"
                    Me.mUIUsernameEdit.FilterProperties(HtmlEdit.PropertyNames.Type) = "SINGLELINE"
                    Me.mUIUsernameEdit.FilterProperties(HtmlEdit.PropertyNames.Title) = Nothing
                    Me.mUIUsernameEdit.FilterProperties(HtmlEdit.PropertyNames.Class) = Nothing
                    Me.mUIUsernameEdit.FilterProperties(HtmlEdit.PropertyNames.ControlDefinition) = "id=dnn_ctr635_Login_Login_ActiveDirector"
                    Me.mUIUsernameEdit.FilterProperties(HtmlEdit.PropertyNames.TagInstance) = "8"
                    Me.mUIUsernameEdit.WindowTitles.Add("Login")
                End If
                Return Me.mUIUsernameEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIUsernameEdit As HtmlEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIGoogleDocument
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = "gsr"
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "False"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = "Google"
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "https://www.google.com/?gws_rd=ssl"
            Me.WindowTitles.Add("Google")
            Me.WindowTitles.Add("coded ui testing - Google Search")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIQEdit() As HtmlEdit
            Get
                If (Me.mUIQEdit Is Nothing) Then
                    Me.mUIQEdit = New HtmlEdit(Me)
                    Me.mUIQEdit.SearchProperties(HtmlEdit.PropertyNames.Id) = "gbqfq"
                    Me.mUIQEdit.SearchProperties(HtmlEdit.PropertyNames.Name) = "q"
                    Me.mUIQEdit.FilterProperties(HtmlEdit.PropertyNames.LabeledBy) = Nothing
                    Me.mUIQEdit.FilterProperties(HtmlEdit.PropertyNames.Type) = "SINGLELINE"
                    Me.mUIQEdit.FilterProperties(HtmlEdit.PropertyNames.Title) = Nothing
                    Me.mUIQEdit.FilterProperties(HtmlEdit.PropertyNames.Class) = "gbqfif"
                    Me.mUIQEdit.FilterProperties(HtmlEdit.PropertyNames.ControlDefinition) = "name=""q"" class=""gbqfif"" id=""gbqfq"" style"
                    Me.mUIQEdit.FilterProperties(HtmlEdit.PropertyNames.TagInstance) = "3"
                    Me.mUIQEdit.WindowTitles.Add("Google")
                End If
                Return Me.mUIQEdit
            End Get
        End Property
        
        Public ReadOnly Property UIIresPane() As HtmlDiv
            Get
                If (Me.mUIIresPane Is Nothing) Then
                    Me.mUIIresPane = New HtmlDiv(Me)
                    Me.mUIIresPane.SearchProperties(HtmlDiv.PropertyNames.Id) = "ires"
                    Me.mUIIresPane.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
                    Me.mUIIresPane.FilterProperties(HtmlDiv.PropertyNames.InnerText) = "Verifying Code by Using UI Automation - "
                    Me.mUIIresPane.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
                    Me.mUIIresPane.FilterProperties(HtmlDiv.PropertyNames.Class) = Nothing
                    Me.mUIIresPane.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "id=""ires"" data-async-context=""query:coded%20ui"""
                    Me.mUIIresPane.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "140"
                    Me.mUIIresPane.WindowTitles.Add("Google")
                End If
                Return Me.mUIIresPane
            End Get
        End Property
        
        Public ReadOnly Property UICenter_colPane() As HtmlDiv
            Get
                If (Me.mUICenter_colPane Is Nothing) Then
                    Me.mUICenter_colPane = New HtmlDiv(Me)
                    Me.mUICenter_colPane.SearchProperties(HtmlDiv.PropertyNames.Id) = "center_col"
                    Me.mUICenter_colPane.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
                    Me.mUICenter_colPane.FilterProperties(HtmlDiv.PropertyNames.InnerText) = ".ads-ad{padding-top:11px;padding-bottom:"
                    Me.mUICenter_colPane.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
                    Me.mUICenter_colPane.FilterProperties(HtmlDiv.PropertyNames.Class) = Nothing
                    Me.mUICenter_colPane.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "id=""center_col"" style=""padding-top: 0px; visibility: visible;"""
                    Me.mUICenter_colPane.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "115"
                    Me.mUICenter_colPane.WindowTitles.Add("Google")
                End If
                Return Me.mUICenter_colPane
            End Get
        End Property
        
        Public ReadOnly Property UITadsPane() As UITadsPane
            Get
                If (Me.mUITadsPane Is Nothing) Then
                    Me.mUITadsPane = New UITadsPane(Me)
                End If
                Return Me.mUITadsPane
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIQEdit As HtmlEdit
        
        Private mUIIresPane As HtmlDiv
        
        Private mUICenter_colPane As HtmlDiv
        
        Private mUITadsPane As UITadsPane
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UITadsPane
        Inherits HtmlDiv
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDiv.PropertyNames.Id) = "tads"
            Me.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.InnerText) = "Why these ads?"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"These ads are based "
            Me.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
            Me.FilterProperties(HtmlDiv.PropertyNames.Class) = "_Yc c"
            Me.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "class=""_Yc c"" id=""tads"" data-ved=""0CBkQGA"""
            Me.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "103"
            Me.WindowTitles.Add("Google")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UICreateeasytomaintainPane() As HtmlDiv
            Get
                If (Me.mUICreateeasytomaintainPane Is Nothing) Then
                    Me.mUICreateeasytomaintainPane = New HtmlDiv(Me)
                    Me.mUICreateeasytomaintainPane.SearchProperties(HtmlDiv.PropertyNames.Id) = Nothing
                    Me.mUICreateeasytomaintainPane.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
                    Me.mUICreateeasytomaintainPane.FilterProperties(HtmlDiv.PropertyNames.InnerText) = "Create easy to maintain tests with Visua"
                    Me.mUICreateeasytomaintainPane.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
                    Me.mUICreateeasytomaintainPane.FilterProperties(HtmlDiv.PropertyNames.Class) = "ads-creative"
                    Me.mUICreateeasytomaintainPane.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "class=""ads-creative"""
                    Me.mUICreateeasytomaintainPane.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "118"
                    Me.mUICreateeasytomaintainPane.WindowTitles.Add("Google")
                End If
                Return Me.mUICreateeasytomaintainPane
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUICreateeasytomaintainPane As HtmlDiv
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UICodeduitestingGoogleDocument
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = "gsr"
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "False"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = "coded ui testing - Google Search"
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "https://www.google.com/?gws_rd=ssl#q=coded+ui+testing"
            Me.WindowTitles.Add("coded ui testing - Google Search")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIHdtbSumPane() As HtmlDiv
            Get
                If (Me.mUIHdtbSumPane Is Nothing) Then
                    Me.mUIHdtbSumPane = New HtmlDiv(Me)
                    Me.mUIHdtbSumPane.SearchProperties(HtmlDiv.PropertyNames.Id) = "hdtbSum"
                    Me.mUIHdtbSumPane.SearchProperties(HtmlDiv.PropertyNames.Name) = Nothing
                    Me.mUIHdtbSumPane.FilterProperties(HtmlDiv.PropertyNames.InnerText) = "Web"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Videos"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Images"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"News"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Shopp"
                    Me.mUIHdtbSumPane.FilterProperties(HtmlDiv.PropertyNames.Title) = Nothing
                    Me.mUIHdtbSumPane.FilterProperties(HtmlDiv.PropertyNames.Class) = Nothing
                    Me.mUIHdtbSumPane.FilterProperties(HtmlDiv.PropertyNames.ControlDefinition) = "id=""hdtbSum"""
                    Me.mUIHdtbSumPane.FilterProperties(HtmlDiv.PropertyNames.TagInstance) = "60"
                    Me.mUIHdtbSumPane.WindowTitles.Add("coded ui testing - Google Search")
                End If
                Return Me.mUIHdtbSumPane
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIHdtbSumPane As HtmlDiv
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIItemWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "TabBandClass"
            Me.WindowTitles.Add("https://home.compaid.com/")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemClient() As UIItemClient
            Get
                If (Me.mUIItemClient Is Nothing) Then
                    Me.mUIItemClient = New UIItemClient(Me)
                End If
                Return Me.mUIItemClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemClient As UIItemClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIItemClient
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.WindowTitles.Add("https://home.compaid.com/")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemWindow() As WinWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New WinWindow(Me)
                    Me.mUIItemWindow.SearchProperties(WinWindow.PropertyNames.ClassName) = "DirectUIHWND"
                    Me.mUIItemWindow.WindowTitles.Add("https://home.compaid.com/")
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemWindow As WinWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIHTMLFormsandInputDocument
        Inherits HtmlDocument
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(HtmlDocument.PropertyNames.Id) = Nothing
            Me.SearchProperties(HtmlDocument.PropertyNames.RedirectingPage) = "False"
            Me.SearchProperties(HtmlDocument.PropertyNames.FrameDocument) = "False"
            Me.FilterProperties(HtmlDocument.PropertyNames.Title) = "HTML Forms and Input"
            Me.FilterProperties(HtmlDocument.PropertyNames.AbsolutePath) = "/html/html_forms.asp"
            Me.FilterProperties(HtmlDocument.PropertyNames.PageUrl) = "http://www.w3schools.com/html/html_forms.asp"
            Me.WindowTitles.Add("HTML Forms and Input")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UILastnameEdit() As HtmlEdit
            Get
                If (Me.mUILastnameEdit Is Nothing) Then
                    Me.mUILastnameEdit = New HtmlEdit(Me)
                    Me.mUILastnameEdit.SearchProperties(HtmlEdit.PropertyNames.Id) = Nothing
                    Me.mUILastnameEdit.SearchProperties(HtmlEdit.PropertyNames.Name) = "lastname"
                    Me.mUILastnameEdit.SearchProperties(HtmlEdit.PropertyNames.LabeledBy) = Nothing
                    Me.mUILastnameEdit.SearchProperties(HtmlEdit.PropertyNames.Type) = "SINGLELINE"
                    Me.mUILastnameEdit.FilterProperties(HtmlEdit.PropertyNames.Title) = Nothing
                    Me.mUILastnameEdit.FilterProperties(HtmlEdit.PropertyNames.Class) = Nothing
                    Me.mUILastnameEdit.FilterProperties(HtmlEdit.PropertyNames.ControlDefinition) = "name=""lastname"" type=""text"" size=""20"""
                    Me.mUILastnameEdit.FilterProperties(HtmlEdit.PropertyNames.TagInstance) = "2"
                    Me.mUILastnameEdit.WindowTitles.Add("HTML Forms and Input")
                End If
                Return Me.mUILastnameEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUILastnameEdit As HtmlEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIChromeGoogleChromeWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Chrome - Google Chrome"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Chrome_WidgetWin_1"
            Me.WindowTitles.Add("Chrome - Google Chrome")
            Me.WindowTitles.Add("Google - Google Chrome")
            Me.WindowTitles.Add("code ui test - Google Search - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAddressandsearchbarGroup() As UIAddressandsearchbarGroup
            Get
                If (Me.mUIAddressandsearchbarGroup Is Nothing) Then
                    Me.mUIAddressandsearchbarGroup = New UIAddressandsearchbarGroup(Me)
                End If
                Return Me.mUIAddressandsearchbarGroup
            End Get
        End Property
        
        Public ReadOnly Property UIChromeLegacyWindowWindow() As UIChromeLegacyWindowWindow
            Get
                If (Me.mUIChromeLegacyWindowWindow Is Nothing) Then
                    Me.mUIChromeLegacyWindowWindow = New UIChromeLegacyWindowWindow(Me)
                End If
                Return Me.mUIChromeLegacyWindowWindow
            End Get
        End Property
        
        Public ReadOnly Property UICodeuitestGoogleSearClient() As UICodeuitestGoogleSearClient
            Get
                If (Me.mUICodeuitestGoogleSearClient Is Nothing) Then
                    Me.mUICodeuitestGoogleSearClient = New UICodeuitestGoogleSearClient(Me)
                End If
                Return Me.mUICodeuitestGoogleSearClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAddressandsearchbarGroup As UIAddressandsearchbarGroup
        
        Private mUIChromeLegacyWindowWindow As UIChromeLegacyWindowWindow
        
        Private mUICodeuitestGoogleSearClient As UICodeuitestGoogleSearClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIAddressandsearchbarGroup
        Inherits WinGroup
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinControl.PropertyNames.Name) = "Address and search bar"
            Me.WindowTitles.Add("Chrome - Google Chrome")
            Me.WindowTitles.Add("Google - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAddressandsearchbarEdit() As WinEdit
            Get
                If (Me.mUIAddressandsearchbarEdit Is Nothing) Then
                    Me.mUIAddressandsearchbarEdit = New WinEdit(Me)
                    Me.mUIAddressandsearchbarEdit.SearchProperties(WinEdit.PropertyNames.Name) = "Address and search bar"
                    Me.mUIAddressandsearchbarEdit.WindowTitles.Add("Chrome - Google Chrome")
                    Me.mUIAddressandsearchbarEdit.WindowTitles.Add("Google - Google Chrome")
                End If
                Return Me.mUIAddressandsearchbarEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAddressandsearchbarEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIChromeLegacyWindowWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "180776064"
            Me.WindowTitles.Add("code ui test - Google Search - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIChromeLegacyWindowClient() As WinClient
            Get
                If (Me.mUIChromeLegacyWindowClient Is Nothing) Then
                    Me.mUIChromeLegacyWindowClient = New WinClient(Me)
                    Me.mUIChromeLegacyWindowClient.SearchProperties(WinControl.PropertyNames.Name) = "Chrome Legacy Window"
                    Me.mUIChromeLegacyWindowClient.WindowTitles.Add("code ui test - Google Search - Google Chrome")
                End If
                Return Me.mUIChromeLegacyWindowClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIChromeLegacyWindowClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UICodeuitestGoogleSearClient
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.WindowTitles.Add("code ui test - Google Search - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIGoogleChromeToolbarToolBar() As WinToolBar
            Get
                If (Me.mUIGoogleChromeToolbarToolBar Is Nothing) Then
                    Me.mUIGoogleChromeToolbarToolBar = New WinToolBar(Me)
                    Me.mUIGoogleChromeToolbarToolBar.SearchProperties(WinToolBar.PropertyNames.Name) = "Google Chrome Toolbar"
                    Me.mUIGoogleChromeToolbarToolBar.WindowTitles.Add("code ui test - Google Search - Google Chrome")
                End If
                Return Me.mUIGoogleChromeToolbarToolBar
            End Get
        End Property
        
        Public ReadOnly Property UIChromeLegacyWindowClient() As WinClient
            Get
                If (Me.mUIChromeLegacyWindowClient Is Nothing) Then
                    Me.mUIChromeLegacyWindowClient = New WinClient(Me)
                    Me.mUIChromeLegacyWindowClient.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild)
                    Me.mUIChromeLegacyWindowClient.WindowTitles.Add("code ui test - Google Search - Google Chrome")
                End If
                Return Me.mUIChromeLegacyWindowClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIGoogleChromeToolbarToolBar As WinToolBar
        
        Private mUIChromeLegacyWindowClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIItemWindow2
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.AccessibleName) = "Desktop"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "#32769"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemWindow1() As UIItemWindow1
            Get
                If (Me.mUIItemWindow1 Is Nothing) Then
                    Me.mUIItemWindow1 = New UIItemWindow1(Me)
                End If
                Return Me.mUIItemWindow1
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemWindow1 As UIItemWindow1
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIItemWindow1
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Shell_TrayWnd"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIDesktopClient() As WinClient
            Get
                If (Me.mUIDesktopClient Is Nothing) Then
                    Me.mUIDesktopClient = New WinClient(Me)
                End If
                Return Me.mUIDesktopClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIDesktopClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UINewTabGoogleChromeWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "New Tab - Google Chrome"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Chrome_WidgetWin_1"
            Me.WindowTitles.Add("New Tab - Google Chrome")
            Me.WindowTitles.Add("HTML Forms and Input - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAddressandsearchbarGroup() As UIAddressandsearchbarGroup1
            Get
                If (Me.mUIAddressandsearchbarGroup Is Nothing) Then
                    Me.mUIAddressandsearchbarGroup = New UIAddressandsearchbarGroup1(Me)
                End If
                Return Me.mUIAddressandsearchbarGroup
            End Get
        End Property
        
        Public ReadOnly Property UIChromeLegacyWindowWindow() As UIChromeLegacyWindowWindow1
            Get
                If (Me.mUIChromeLegacyWindowWindow Is Nothing) Then
                    Me.mUIChromeLegacyWindowWindow = New UIChromeLegacyWindowWindow1(Me)
                End If
                Return Me.mUIChromeLegacyWindowWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAddressandsearchbarGroup As UIAddressandsearchbarGroup1
        
        Private mUIChromeLegacyWindowWindow As UIChromeLegacyWindowWindow1
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIAddressandsearchbarGroup1
        Inherits WinGroup
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinControl.PropertyNames.Name) = "Address and search bar"
            Me.WindowTitles.Add("New Tab - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIAddressandsearchbarEdit() As WinEdit
            Get
                If (Me.mUIAddressandsearchbarEdit Is Nothing) Then
                    Me.mUIAddressandsearchbarEdit = New WinEdit(Me)
                    Me.mUIAddressandsearchbarEdit.SearchProperties(WinEdit.PropertyNames.Name) = "Address and search bar"
                    Me.mUIAddressandsearchbarEdit.WindowTitles.Add("New Tab - Google Chrome")
                End If
                Return Me.mUIAddressandsearchbarEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIAddressandsearchbarEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.30501.0")>  _
    Public Class UIChromeLegacyWindowWindow1
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "135080384"
            Me.WindowTitles.Add("HTML Forms and Input - Google Chrome")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIChromeLegacyWindowClient() As WinClient
            Get
                If (Me.mUIChromeLegacyWindowClient Is Nothing) Then
                    Me.mUIChromeLegacyWindowClient = New WinClient(Me)
                    Me.mUIChromeLegacyWindowClient.SearchProperties(WinControl.PropertyNames.Name) = "Chrome Legacy Window"
                    Me.mUIChromeLegacyWindowClient.WindowTitles.Add("HTML Forms and Input - Google Chrome")
                End If
                Return Me.mUIChromeLegacyWindowClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIChromeLegacyWindowClient As WinClient
        #End Region
    End Class
End Namespace
