'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property Id As Integer
    Public Property FormSimpleZeroId As Integer
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property AddressLine3 As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property DateCreated As Date
    Public Property LastChangeUser As String
    Public Property LastChangeDate As Date
    Public Property AddressTypeId As Integer

    Public Overridable Property FormSimpleZero As FormSimpleZero
    Public Overridable Property AddressTypeOptionList As AddressTypeOptionList

End Class
