'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ApplicationExtendedProperty
    Public Property ApplicationId As String
    Public Property KeyId As String
    Public Property Value As String
    Public Property DateCreated As Date
    Public Property DateExpired As Date

End Class
