'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
Partial Public Class FormSimpleZero
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(errormessageresourceType:=GetType(Reference.John.Resources.Resources.RequiredMessages), errormessageResourcename:="Id")>
 Public Property Id As Integer
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(errormessageresourceType:=GetType(Reference.John.Resources.Resources.RequiredMessages), errormessageResourcename:="FirstName")>
   <StringLengthAttribute(50, ErrorMessage:="First Name cannot be longer than 50 characters.")>
    Public Property FirstName As String
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(errormessageresourceType:=GetType(Reference.John.Resources.Resources.RequiredMessages), errormessageResourcename:="LastName")>
   <StringLengthAttribute(50, ErrorMessage:="Last Name cannot be longer than 50 characters.")>
 Public Property LastName As String
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(errormessageresourceType:=GetType(Reference.John.Resources.Resources.RequiredMessages), errormessageResourcename:="GenderId")>
 Public Property GenderId As Integer
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Property RaceId As Nullable(Of Integer)
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Property RegionId As Nullable(Of Integer)
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Property EthnicityId As Nullable(Of Integer)
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(errormessageresourceType:=GetType(Reference.John.Resources.Resources.RequiredMessages), errormessageResourcename:="DateCreated")>
 Public Property DateCreated As Date
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    <StringLengthAttribute(50, ErrorMessage:="Last Change User cannot be longer than 50 characters.")>
 Public Property LastChangeUser As String
    ''' <summary>
    ''' #TODO Populate Model Descriptions
    ''' </summary>
    ''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(errormessageresourceType:=GetType(Reference.John.Resources.Resources.RequiredMessages), errormessageResourcename:="LastChangeDate")>
 Public Property LastChangeDate As Date

    Public Overridable Property EthnicityOptionList As EthnicityOptionList
    Public Overridable Property GenderOptionList As GenderOptionList
    Public Overridable Property RaceOptionList As RaceOptionList
    Public Overridable Property RegionOptionList As RegionOptionList
    Public Overridable Property Addresses As ICollection(Of Address) = New HashSet(Of Address)

End Class
