'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FormSimpleZero
    Public Property Id As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property GenderId As Nullable(Of Integer)
    Public Property RaceId As Nullable(Of Integer)
    Public Property RegionId As Nullable(Of Integer)
    Public Property EthnicityId As Nullable(Of Integer)
    Public Property DateCreated As Date
    Public Property LastChangeUser As String
    Public Property LastChangeDate As Date

    Public Overridable Property EthnicityOptionList As EthnicityOptionList
    Public Overridable Property GenderOptionList As GenderOptionList
    Public Overridable Property RaceOptionList As RaceOptionList
    Public Overridable Property RegionOptionList As RegionOptionList
    Public Overridable Property Addresses As ICollection(Of Address) = New HashSet(Of Address)

End Class
