'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
Partial Public Class SearchResult
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Form Id is required.")>
    Public Property FormId As Integer
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="First Name is required.")>
	<StringLengthAttribute(50, ErrorMessage:="First Name cannot be longer than 50 characters.")>
    Public Property FirstName As String
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Last Name is required.")>
	<StringLengthAttribute(50, ErrorMessage:="Last Name cannot be longer than 50 characters.")>
    Public Property LastName As String
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Property GenderId As Nullable(Of Integer)
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Property RaceId As Nullable(Of Integer)
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Property RegionId As Nullable(Of Integer)
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Property EthnicityId As Nullable(Of Integer)
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Date Created is required.")>
    Public Property DateCreated As Date
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Last Change User is required.")>
	<StringLengthAttribute(50, ErrorMessage:="Last Change User cannot be longer than 50 characters.")>
    Public Property LastChangeUser As String
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Last Change Date is required.")>
    Public Property LastChangeDate As Date
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Ethnicity Name is required.")>
	<StringLengthAttribute(50, ErrorMessage:="Ethnicity Name cannot be longer than 50 characters.")>
    Public Property EthnicityName As String
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Gender Name is required.")>
	<StringLengthAttribute(50, ErrorMessage:="Gender Name cannot be longer than 50 characters.")>
    Public Property GenderName As String

End Class
