'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.CodeDom.Compiler
Imports System.Data.Entity.Core.Metadata.Edm
Imports System.Data.Entity.Infrastructure.MappingViews

<Assembly: DbMappingViewCacheTypeAttribute(
    GetType(Reference.John.Model.Reference_JohnEntities),
    GetType(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets3a27f9b8ad055a413f1689ea0a4dad69caa29d30702ce9cb25fdf21a6e07c434))>

Namespace Edm_EntityMappingGeneratedViews

    ''' <summary>
    ''' Implements a mapping view cache.
    ''' </summary>
    <GeneratedCode("Entity Framework Power Tools", "0.9.0.0")>
    Friend NotInheritable Class ViewsForBaseEntitySets3a27f9b8ad055a413f1689ea0a4dad69caa29d30702ce9cb25fdf21a6e07c434
        Inherits DbMappingViewCache

        ''' <summary>
        ''' Gets a hash value computed over the mapping closure.
        ''' </summary>
        Public Overrides ReadOnly Property MappingHashValue As String
            Get
                Return "3a27f9b8ad055a413f1689ea0a4dad69caa29d30702ce9cb25fdf21a6e07c434"
            End Get
        End Property

        ''' <summary>
        ''' Gets a view corresponding to the specified extent.
        ''' </summary>
        ''' <param name="extent">The extent.</param>
        ''' <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        Public Overrides Function GetView(extent As EntitySetBase) As DbMappingView
            If extent Is Nothing Then
                Throw New ArgumentNullException("extent")
            End If

            Dim extentName = extent.EntityContainer.Name & "." & extent.Name

            If extentName = "ReferenceJohnModelStoreContainer.Address" Then
                Return GetView0()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.AddressTypeOptionList" Then
                Return GetView1()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.EthnicityOptionList" Then
                Return GetView2()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.FormSimpleZero" Then
                Return GetView3()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.FormSimpleZeroHistory" Then
                Return GetView4()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.GenderOptionList" Then
                Return GetView5()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.RaceOptionList" Then
                Return GetView6()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.RegionOptionList" Then
                Return GetView7()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.Entity" Then
                Return GetView8()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.FormEntity_xref" Then
                Return GetView9()
            End If

            If extentName = "Reference_JohnEntities.Addresses" Then
                Return GetView10()
            End If

            If extentName = "Reference_JohnEntities.AddressTypeOptionLists" Then
                Return GetView11()
            End If

            If extentName = "Reference_JohnEntities.EthnicityOptionLists" Then
                Return GetView12()
            End If

            If extentName = "Reference_JohnEntities.FormSimpleZeroes" Then
                Return GetView13()
            End If

            If extentName = "Reference_JohnEntities.FormSimpleZeroHistories" Then
                Return GetView14()
            End If

            If extentName = "Reference_JohnEntities.GenderOptionLists" Then
                Return GetView15()
            End If

            If extentName = "Reference_JohnEntities.RaceOptionLists" Then
                Return GetView16()
            End If

            If extentName = "Reference_JohnEntities.RegionOptionLists" Then
                Return GetView17()
            End If

            If extentName = "Reference_JohnEntities.Entities" Then
                Return GetView18()
            End If

            If extentName = "Reference_JohnEntities.FormEntity_xref" Then
                Return GetView19()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.ApplicationExtendedProperties" Then
                Return GetView20()
            End If

            If extentName = "Reference_JohnEntities.ApplicationExtendedProperties" Then
                Return GetView21()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.UserExtendedProperties" Then
                Return GetView22()
            End If

            If extentName = "Reference_JohnEntities.UserExtendedProperties" Then
                Return GetView23()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.SearchResults" Then
                Return GetView24()
            End If

            If extentName = "Reference_JohnEntities.SearchResults" Then
                Return GetView25()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.FileStore" Then
                Return GetView26()
            End If

            If extentName = "Reference_JohnEntities.FileStores" Then
                Return GetView27()
            End If

            If extentName = "ReferenceJohnModelStoreContainer.AuditLog" Then
                Return GetView28()
            End If

            If extentName = "Reference_JohnEntities.AuditLogs" Then
                Return GetView29()
            End If

            Return Nothing
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.Address.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView0() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing Address" & vbCrLf &
                "        [Reference.John.Model.Store.Address](T1.Address_Id, T1.Address_FormSimpleZeroId, T1.Address_AddressTypeId, T1.Address_AddressLine1, T1.Address_AddressLine2, T1.Address_AddressLine3, T1.Address_City, T1.Address_State, T1.Address_Zip, T1.Address_DateCreated, T1.Address_LastChangeUser, T1.Address_LastChangeDate, T1.Address_ClientToken, T1.Address_RowVersion)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.Id AS Address_Id, " & vbCrLf &
                "            T.FormSimpleZeroId AS Address_FormSimpleZeroId, " & vbCrLf &
                "            T.AddressTypeId AS Address_AddressTypeId, " & vbCrLf &
                "            T.AddressLine1 AS Address_AddressLine1, " & vbCrLf &
                "            T.AddressLine2 AS Address_AddressLine2, " & vbCrLf &
                "            T.AddressLine3 AS Address_AddressLine3, " & vbCrLf &
                "            T.City AS Address_City, " & vbCrLf &
                "            T.State AS Address_State, " & vbCrLf &
                "            T.Zip AS Address_Zip, " & vbCrLf &
                "            T.DateCreated AS Address_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS Address_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS Address_LastChangeDate, " & vbCrLf &
                "            T.ClientToken AS Address_ClientToken, " & vbCrLf &
                "            T.RowVersion AS Address_RowVersion, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.Addresses AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.AddressTypeOptionList.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView1() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing AddressTypeOptionList" & vbCrLf &
                "        [Reference.John.Model.Store.AddressTypeOptionList](T1.AddressTypeOptionList_AddressTypeId, T1.AddressTypeOptionList_Name, T1.AddressTypeOptionList_SortOrder, T1.AddressTypeOptionList_IsActive, T1.AddressTypeOptionList_StartDate, T1.AddressTypeOptionList_EndDate, T1.AddressTypeOptionList_DateCreated, T1.AddressTypeOptionList_LastChangeUser, T1.AddressTypeOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.AddressTypeId AS AddressTypeOptionList_AddressTypeId, " & vbCrLf &
                "            T.Name AS AddressTypeOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS AddressTypeOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS AddressTypeOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS AddressTypeOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS AddressTypeOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS AddressTypeOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS AddressTypeOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS AddressTypeOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.AddressTypeOptionLists AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.EthnicityOptionList.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView2() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing EthnicityOptionList" & vbCrLf &
                "        [Reference.John.Model.Store.EthnicityOptionList](T1.EthnicityOptionList_EthnicityId, T1.EthnicityOptionList_Name, T1.EthnicityOptionList_SortOrder, T1.EthnicityOptionList_IsActive, T1.EthnicityOptionList_StartDate, T1.EthnicityOptionList_EndDate, T1.EthnicityOptionList_DateCreated, T1.EthnicityOptionList_LastChangeUser, T1.EthnicityOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.EthnicityId AS EthnicityOptionList_EthnicityId, " & vbCrLf &
                "            T.Name AS EthnicityOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS EthnicityOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS EthnicityOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS EthnicityOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS EthnicityOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS EthnicityOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS EthnicityOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS EthnicityOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.EthnicityOptionLists AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.FormSimpleZero.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView3() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing FormSimpleZero" & vbCrLf &
                "        [Reference.John.Model.Store.FormSimpleZero](T1.FormSimpleZero_Id, T1.FormSimpleZero_FirstName, T1.FormSimpleZero_LastName, T1.FormSimpleZero_GenderId, T1.FormSimpleZero_RaceId, T1.FormSimpleZero_RegionId, T1.FormSimpleZero_EthnicityId, T1.FormSimpleZero_DateCreated, T1.FormSimpleZero_LastChangeUser, T1.FormSimpleZero_LastChangeDate, T1.FormSimpleZero_ClientToken, T1.FormSimpleZero_RowVersion)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.Id AS FormSimpleZero_Id, " & vbCrLf &
                "            T.FirstName AS FormSimpleZero_FirstName, " & vbCrLf &
                "            T.LastName AS FormSimpleZero_LastName, " & vbCrLf &
                "            T.GenderId AS FormSimpleZero_GenderId, " & vbCrLf &
                "            T.RaceId AS FormSimpleZero_RaceId, " & vbCrLf &
                "            T.RegionId AS FormSimpleZero_RegionId, " & vbCrLf &
                "            T.EthnicityId AS FormSimpleZero_EthnicityId, " & vbCrLf &
                "            T.DateCreated AS FormSimpleZero_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS FormSimpleZero_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS FormSimpleZero_LastChangeDate, " & vbCrLf &
                "            T.ClientToken AS FormSimpleZero_ClientToken, " & vbCrLf &
                "            T.RowVersion AS FormSimpleZero_RowVersion, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.FormSimpleZeroes AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.FormSimpleZeroHistory.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView4() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing FormSimpleZeroHistory" & vbCrLf &
                "        [Reference.John.Model.Store.FormSimpleZeroHistory](T1.FormSimpleZeroHistory_HistoryId, T1.FormSimpleZeroHistory_Id, T1.FormSimpleZeroHistory_FirstName, T1.FormSimpleZeroHistory_LastName, T1.FormSimpleZeroHistory_GenderId, T1.FormSimpleZeroHistory_RaceId, T1.FormSimpleZeroHistory_RegionId, T1.FormSimpleZeroHistory_EthnicityId, T1.FormSimpleZeroHistory_DateCreated, T1.FormSimpleZeroHistory_LastChangeUser, T1.FormSimpleZeroHistory_LastChangeDate, T1.FormSimpleZeroHistory_ClientToken, T1.FormSimpleZeroHistory_RowVersion)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.HistoryId AS FormSimpleZeroHistory_HistoryId, " & vbCrLf &
                "            T.Id AS FormSimpleZeroHistory_Id, " & vbCrLf &
                "            T.FirstName AS FormSimpleZeroHistory_FirstName, " & vbCrLf &
                "            T.LastName AS FormSimpleZeroHistory_LastName, " & vbCrLf &
                "            T.GenderId AS FormSimpleZeroHistory_GenderId, " & vbCrLf &
                "            T.RaceId AS FormSimpleZeroHistory_RaceId, " & vbCrLf &
                "            T.RegionId AS FormSimpleZeroHistory_RegionId, " & vbCrLf &
                "            T.EthnicityId AS FormSimpleZeroHistory_EthnicityId, " & vbCrLf &
                "            T.DateCreated AS FormSimpleZeroHistory_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS FormSimpleZeroHistory_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS FormSimpleZeroHistory_LastChangeDate, " & vbCrLf &
                "            T.ClientToken AS FormSimpleZeroHistory_ClientToken, " & vbCrLf &
                "            T.RowVersion AS FormSimpleZeroHistory_RowVersion, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.FormSimpleZeroHistories AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.GenderOptionList.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView5() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing GenderOptionList" & vbCrLf &
                "        [Reference.John.Model.Store.GenderOptionList](T1.GenderOptionList_GenderId, T1.GenderOptionList_Name, T1.GenderOptionList_SortOrder, T1.GenderOptionList_IsActive, T1.GenderOptionList_StartDate, T1.GenderOptionList_EndDate, T1.GenderOptionList_DateCreated, T1.GenderOptionList_LastChangeUser, T1.GenderOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.GenderId AS GenderOptionList_GenderId, " & vbCrLf &
                "            T.Name AS GenderOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS GenderOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS GenderOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS GenderOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS GenderOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS GenderOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS GenderOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS GenderOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.GenderOptionLists AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.RaceOptionList.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView6() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing RaceOptionList" & vbCrLf &
                "        [Reference.John.Model.Store.RaceOptionList](T1.RaceOptionList_RaceId, T1.RaceOptionList_Name, T1.RaceOptionList_SortOrder, T1.RaceOptionList_IsActive, T1.RaceOptionList_StartDate, T1.RaceOptionList_EndDate, T1.RaceOptionList_DateCreated, T1.RaceOptionList_LastChangeUser, T1.RaceOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.RaceId AS RaceOptionList_RaceId, " & vbCrLf &
                "            T.Name AS RaceOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS RaceOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS RaceOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS RaceOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS RaceOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS RaceOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS RaceOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS RaceOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.RaceOptionLists AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.RegionOptionList.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView7() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing RegionOptionList" & vbCrLf &
                "        [Reference.John.Model.Store.RegionOptionList](T1.RegionOptionList_RegionId, T1.RegionOptionList_Name, T1.RegionOptionList_SortOrder, T1.RegionOptionList_IsActive, T1.RegionOptionList_StartDate, T1.RegionOptionList_EndDate, T1.RegionOptionList_DateCreated, T1.RegionOptionList_LastChangeUser, T1.RegionOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.RegionId AS RegionOptionList_RegionId, " & vbCrLf &
                "            T.Name AS RegionOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS RegionOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS RegionOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS RegionOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS RegionOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS RegionOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS RegionOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS RegionOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.RegionOptionLists AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.Entity.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView8() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing Entity" & vbCrLf &
                "        [Reference.John.Model.Store.Entity](T1.Entity_EntityId, T1.Entity_EntityName, T1.Entity_IsActive, T1.Entity_StartDate, T1.Entity_EndDate, T1.Entity_DateCreated, T1.Entity_LastChangeUser, T1.Entity_LastChangeDate, T1.Entity_ClientToken, T1.Entity_RowVersion)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.EntityId AS Entity_EntityId, " & vbCrLf &
                "            T.EntityName AS Entity_EntityName, " & vbCrLf &
                "            T.IsActive AS Entity_IsActive, " & vbCrLf &
                "            T.StartDate AS Entity_StartDate, " & vbCrLf &
                "            T.EndDate AS Entity_EndDate, " & vbCrLf &
                "            T.DateCreated AS Entity_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS Entity_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS Entity_LastChangeDate, " & vbCrLf &
                "            T.ClientToken AS Entity_ClientToken, " & vbCrLf &
                "            T.RowVersion AS Entity_RowVersion, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.Entities AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.FormEntity_xref.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView9() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing FormEntity_xref" & vbCrLf &
                "        [Reference.John.Model.Store.FormEntity_xref](T1.[FormEntity_xref.FormId], T1.[FormEntity_xref.EntityId], T1.[FormEntity_xref.RelationshipType], T1.[FormEntity_xref.RelationshipStatus], T1.[FormEntity_xref.RelationshipDescription], T1.[FormEntity_xref.IsActive], T1.[FormEntity_xref.StartDate], T1.[FormEntity_xref.EndDate], T1.[FormEntity_xref.DateCreated], T1.[FormEntity_xref.LastChangeUser], T1.[FormEntity_xref.LastChangeDate], T1.[FormEntity_xref.ClientToken], T1.[FormEntity_xref.RowVersion])" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.FormId AS [FormEntity_xref.FormId], " & vbCrLf &
                "            T.EntityId AS [FormEntity_xref.EntityId], " & vbCrLf &
                "            T.RelationshipType AS [FormEntity_xref.RelationshipType], " & vbCrLf &
                "            T.RelationshipStatus AS [FormEntity_xref.RelationshipStatus], " & vbCrLf &
                "            T.RelationshipDescription AS [FormEntity_xref.RelationshipDescription], " & vbCrLf &
                "            T.IsActive AS [FormEntity_xref.IsActive], " & vbCrLf &
                "            T.StartDate AS [FormEntity_xref.StartDate], " & vbCrLf &
                "            T.EndDate AS [FormEntity_xref.EndDate], " & vbCrLf &
                "            T.DateCreated AS [FormEntity_xref.DateCreated], " & vbCrLf &
                "            T.LastChangeUser AS [FormEntity_xref.LastChangeUser], " & vbCrLf &
                "            T.LastChangeDate AS [FormEntity_xref.LastChangeDate], " & vbCrLf &
                "            T.ClientToken AS [FormEntity_xref.ClientToken], " & vbCrLf &
                "            T.RowVersion AS [FormEntity_xref.RowVersion], " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.FormEntity_xref AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.Addresses.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView10() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing Addresses" & vbCrLf &
                "        [Reference.John.Model.Address](T1.Address_Id, T1.Address_FormSimpleZeroId, T1.Address_AddressTypeId, T1.Address_AddressLine1, T1.Address_AddressLine2, T1.Address_AddressLine3, T1.Address_City, T1.Address_State, T1.Address_Zip, T1.Address_DateCreated, T1.Address_LastChangeUser, T1.Address_LastChangeDate, T1.Address_ClientToken, T1.Address_RowVersion)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.Id AS Address_Id, " & vbCrLf &
                "            T.FormSimpleZeroId AS Address_FormSimpleZeroId, " & vbCrLf &
                "            T.AddressTypeId AS Address_AddressTypeId, " & vbCrLf &
                "            T.AddressLine1 AS Address_AddressLine1, " & vbCrLf &
                "            T.AddressLine2 AS Address_AddressLine2, " & vbCrLf &
                "            T.AddressLine3 AS Address_AddressLine3, " & vbCrLf &
                "            T.City AS Address_City, " & vbCrLf &
                "            T.State AS Address_State, " & vbCrLf &
                "            T.Zip AS Address_Zip, " & vbCrLf &
                "            T.DateCreated AS Address_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS Address_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS Address_LastChangeDate, " & vbCrLf &
                "            T.ClientToken AS Address_ClientToken, " & vbCrLf &
                "            T.RowVersion AS Address_RowVersion, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.Address AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.AddressTypeOptionLists.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView11() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing AddressTypeOptionLists" & vbCrLf &
                "        [Reference.John.Model.AddressTypeOptionList](T1.AddressTypeOptionList_AddressTypeId, T1.AddressTypeOptionList_Name, T1.AddressTypeOptionList_SortOrder, T1.AddressTypeOptionList_IsActive, T1.AddressTypeOptionList_StartDate, T1.AddressTypeOptionList_EndDate, T1.AddressTypeOptionList_DateCreated, T1.AddressTypeOptionList_LastChangeUser, T1.AddressTypeOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.AddressTypeId AS AddressTypeOptionList_AddressTypeId, " & vbCrLf &
                "            T.Name AS AddressTypeOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS AddressTypeOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS AddressTypeOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS AddressTypeOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS AddressTypeOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS AddressTypeOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS AddressTypeOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS AddressTypeOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.AddressTypeOptionList AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.EthnicityOptionLists.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView12() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing EthnicityOptionLists" & vbCrLf &
                "        [Reference.John.Model.EthnicityOptionList](T1.EthnicityOptionList_EthnicityId, T1.EthnicityOptionList_Name, T1.EthnicityOptionList_SortOrder, T1.EthnicityOptionList_IsActive, T1.EthnicityOptionList_StartDate, T1.EthnicityOptionList_EndDate, T1.EthnicityOptionList_DateCreated, T1.EthnicityOptionList_LastChangeUser, T1.EthnicityOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.EthnicityId AS EthnicityOptionList_EthnicityId, " & vbCrLf &
                "            T.Name AS EthnicityOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS EthnicityOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS EthnicityOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS EthnicityOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS EthnicityOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS EthnicityOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS EthnicityOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS EthnicityOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.EthnicityOptionList AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.FormSimpleZeroes.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView13() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing FormSimpleZeroes" & vbCrLf &
                "        [Reference.John.Model.FormSimpleZero](T1.FormSimpleZero_Id, T1.FormSimpleZero_FirstName, T1.FormSimpleZero_LastName, T1.FormSimpleZero_GenderId, T1.FormSimpleZero_RaceId, T1.FormSimpleZero_RegionId, T1.FormSimpleZero_EthnicityId, T1.FormSimpleZero_DateCreated, T1.FormSimpleZero_LastChangeUser, T1.FormSimpleZero_LastChangeDate, T1.FormSimpleZero_ClientToken, T1.FormSimpleZero_RowVersion)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.Id AS FormSimpleZero_Id, " & vbCrLf &
                "            T.FirstName AS FormSimpleZero_FirstName, " & vbCrLf &
                "            T.LastName AS FormSimpleZero_LastName, " & vbCrLf &
                "            T.GenderId AS FormSimpleZero_GenderId, " & vbCrLf &
                "            T.RaceId AS FormSimpleZero_RaceId, " & vbCrLf &
                "            T.RegionId AS FormSimpleZero_RegionId, " & vbCrLf &
                "            T.EthnicityId AS FormSimpleZero_EthnicityId, " & vbCrLf &
                "            T.DateCreated AS FormSimpleZero_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS FormSimpleZero_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS FormSimpleZero_LastChangeDate, " & vbCrLf &
                "            T.ClientToken AS FormSimpleZero_ClientToken, " & vbCrLf &
                "            T.RowVersion AS FormSimpleZero_RowVersion, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.FormSimpleZero AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.FormSimpleZeroHistories.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView14() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing FormSimpleZeroHistories" & vbCrLf &
                "        [Reference.John.Model.FormSimpleZeroHistory](T1.FormSimpleZeroHistory_HistoryId, T1.FormSimpleZeroHistory_Id, T1.FormSimpleZeroHistory_FirstName, T1.FormSimpleZeroHistory_LastName, T1.FormSimpleZeroHistory_GenderId, T1.FormSimpleZeroHistory_RaceId, T1.FormSimpleZeroHistory_RegionId, T1.FormSimpleZeroHistory_EthnicityId, T1.FormSimpleZeroHistory_DateCreated, T1.FormSimpleZeroHistory_LastChangeUser, T1.FormSimpleZeroHistory_LastChangeDate, T1.FormSimpleZeroHistory_ClientToken, T1.FormSimpleZeroHistory_RowVersion)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.HistoryId AS FormSimpleZeroHistory_HistoryId, " & vbCrLf &
                "            T.Id AS FormSimpleZeroHistory_Id, " & vbCrLf &
                "            T.FirstName AS FormSimpleZeroHistory_FirstName, " & vbCrLf &
                "            T.LastName AS FormSimpleZeroHistory_LastName, " & vbCrLf &
                "            T.GenderId AS FormSimpleZeroHistory_GenderId, " & vbCrLf &
                "            T.RaceId AS FormSimpleZeroHistory_RaceId, " & vbCrLf &
                "            T.RegionId AS FormSimpleZeroHistory_RegionId, " & vbCrLf &
                "            T.EthnicityId AS FormSimpleZeroHistory_EthnicityId, " & vbCrLf &
                "            T.DateCreated AS FormSimpleZeroHistory_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS FormSimpleZeroHistory_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS FormSimpleZeroHistory_LastChangeDate, " & vbCrLf &
                "            T.ClientToken AS FormSimpleZeroHistory_ClientToken, " & vbCrLf &
                "            T.RowVersion AS FormSimpleZeroHistory_RowVersion, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.FormSimpleZeroHistory AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.GenderOptionLists.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView15() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing GenderOptionLists" & vbCrLf &
                "        [Reference.John.Model.GenderOptionList](T1.GenderOptionList_GenderId, T1.GenderOptionList_Name, T1.GenderOptionList_SortOrder, T1.GenderOptionList_IsActive, T1.GenderOptionList_StartDate, T1.GenderOptionList_EndDate, T1.GenderOptionList_DateCreated, T1.GenderOptionList_LastChangeUser, T1.GenderOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.GenderId AS GenderOptionList_GenderId, " & vbCrLf &
                "            T.Name AS GenderOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS GenderOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS GenderOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS GenderOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS GenderOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS GenderOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS GenderOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS GenderOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.GenderOptionList AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.RaceOptionLists.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView16() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing RaceOptionLists" & vbCrLf &
                "        [Reference.John.Model.RaceOptionList](T1.RaceOptionList_RaceId, T1.RaceOptionList_Name, T1.RaceOptionList_SortOrder, T1.RaceOptionList_IsActive, T1.RaceOptionList_StartDate, T1.RaceOptionList_EndDate, T1.RaceOptionList_DateCreated, T1.RaceOptionList_LastChangeUser, T1.RaceOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.RaceId AS RaceOptionList_RaceId, " & vbCrLf &
                "            T.Name AS RaceOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS RaceOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS RaceOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS RaceOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS RaceOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS RaceOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS RaceOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS RaceOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.RaceOptionList AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.RegionOptionLists.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView17() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing RegionOptionLists" & vbCrLf &
                "        [Reference.John.Model.RegionOptionList](T1.RegionOptionList_RegionId, T1.RegionOptionList_Name, T1.RegionOptionList_SortOrder, T1.RegionOptionList_IsActive, T1.RegionOptionList_StartDate, T1.RegionOptionList_EndDate, T1.RegionOptionList_DateCreated, T1.RegionOptionList_LastChangeUser, T1.RegionOptionList_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.RegionId AS RegionOptionList_RegionId, " & vbCrLf &
                "            T.Name AS RegionOptionList_Name, " & vbCrLf &
                "            T.SortOrder AS RegionOptionList_SortOrder, " & vbCrLf &
                "            T.IsActive AS RegionOptionList_IsActive, " & vbCrLf &
                "            T.StartDate AS RegionOptionList_StartDate, " & vbCrLf &
                "            T.EndDate AS RegionOptionList_EndDate, " & vbCrLf &
                "            T.DateCreated AS RegionOptionList_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS RegionOptionList_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS RegionOptionList_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.RegionOptionList AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.Entities.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView18() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing Entities" & vbCrLf &
                "        [Reference.John.Model.Entity](T1.Entity_EntityId, T1.Entity_EntityName, T1.Entity_IsActive, T1.Entity_StartDate, T1.Entity_EndDate, T1.Entity_DateCreated, T1.Entity_LastChangeUser, T1.Entity_LastChangeDate, T1.Entity_ClientToken, T1.Entity_RowVersion)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.EntityId AS Entity_EntityId, " & vbCrLf &
                "            T.EntityName AS Entity_EntityName, " & vbCrLf &
                "            T.IsActive AS Entity_IsActive, " & vbCrLf &
                "            T.StartDate AS Entity_StartDate, " & vbCrLf &
                "            T.EndDate AS Entity_EndDate, " & vbCrLf &
                "            T.DateCreated AS Entity_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS Entity_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS Entity_LastChangeDate, " & vbCrLf &
                "            T.ClientToken AS Entity_ClientToken, " & vbCrLf &
                "            T.RowVersion AS Entity_RowVersion, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.Entity AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.FormEntity_xref.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView19() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing FormEntity_xref" & vbCrLf &
                "        [Reference.John.Model.FormEntity_xref](T1.[FormEntity_xref.FormId], T1.[FormEntity_xref.EntityId], T1.[FormEntity_xref.RelationshipType], T1.[FormEntity_xref.RelationshipStatus], T1.[FormEntity_xref.RelationshipDescription], T1.[FormEntity_xref.IsActive], T1.[FormEntity_xref.StartDate], T1.[FormEntity_xref.EndDate], T1.[FormEntity_xref.DateCreated], T1.[FormEntity_xref.LastChangeUser], T1.[FormEntity_xref.LastChangeDate], T1.[FormEntity_xref.ClientToken], T1.[FormEntity_xref.RowVersion])" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.FormId AS [FormEntity_xref.FormId], " & vbCrLf &
                "            T.EntityId AS [FormEntity_xref.EntityId], " & vbCrLf &
                "            T.RelationshipType AS [FormEntity_xref.RelationshipType], " & vbCrLf &
                "            T.RelationshipStatus AS [FormEntity_xref.RelationshipStatus], " & vbCrLf &
                "            T.RelationshipDescription AS [FormEntity_xref.RelationshipDescription], " & vbCrLf &
                "            T.IsActive AS [FormEntity_xref.IsActive], " & vbCrLf &
                "            T.StartDate AS [FormEntity_xref.StartDate], " & vbCrLf &
                "            T.EndDate AS [FormEntity_xref.EndDate], " & vbCrLf &
                "            T.DateCreated AS [FormEntity_xref.DateCreated], " & vbCrLf &
                "            T.LastChangeUser AS [FormEntity_xref.LastChangeUser], " & vbCrLf &
                "            T.LastChangeDate AS [FormEntity_xref.LastChangeDate], " & vbCrLf &
                "            T.ClientToken AS [FormEntity_xref.ClientToken], " & vbCrLf &
                "            T.RowVersion AS [FormEntity_xref.RowVersion], " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.FormEntity_xref AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.ApplicationExtendedProperties.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView20() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing ApplicationExtendedProperties" & vbCrLf &
                "        [Reference.John.Model.Store.ApplicationExtendedProperties](T1.ApplicationExtendedProperties_ApplicationId, T1.ApplicationExtendedProperties_KeyId, T1.ApplicationExtendedProperties_Value, T1.ApplicationExtendedProperties_DateCreated, T1.ApplicationExtendedProperties_DateExpired, T1.ApplicationExtendedProperties_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.ApplicationId AS ApplicationExtendedProperties_ApplicationId, " & vbCrLf &
                "            T.KeyId AS ApplicationExtendedProperties_KeyId, " & vbCrLf &
                "            T.[Value] AS ApplicationExtendedProperties_Value, " & vbCrLf &
                "            T.DateCreated AS ApplicationExtendedProperties_DateCreated, " & vbCrLf &
                "            T.DateExpired AS ApplicationExtendedProperties_DateExpired, " & vbCrLf &
                "            T.LastChangeDate AS ApplicationExtendedProperties_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.ApplicationExtendedProperties AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.ApplicationExtendedProperties.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView21() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing ApplicationExtendedProperties" & vbCrLf &
                "        [Reference.John.Model.ApplicationExtendedProperty](T1.ApplicationExtendedProperty_ApplicationId, T1.ApplicationExtendedProperty_KeyId, T1.ApplicationExtendedProperty_Value, T1.ApplicationExtendedProperty_DateCreated, T1.ApplicationExtendedProperty_DateExpired, T1.ApplicationExtendedProperty_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.ApplicationId AS ApplicationExtendedProperty_ApplicationId, " & vbCrLf &
                "            T.KeyId AS ApplicationExtendedProperty_KeyId, " & vbCrLf &
                "            T.[Value] AS ApplicationExtendedProperty_Value, " & vbCrLf &
                "            T.DateCreated AS ApplicationExtendedProperty_DateCreated, " & vbCrLf &
                "            T.DateExpired AS ApplicationExtendedProperty_DateExpired, " & vbCrLf &
                "            T.LastChangeDate AS ApplicationExtendedProperty_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.ApplicationExtendedProperties AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.UserExtendedProperties.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView22() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing UserExtendedProperties" & vbCrLf &
                "        [Reference.John.Model.Store.UserExtendedProperties](T1.UserExtendedProperties_UserId, T1.UserExtendedProperties_KeyId, T1.UserExtendedProperties_Value, T1.UserExtendedProperties_DateCreated, T1.UserExtendedProperties_DateExpired, T1.UserExtendedProperties_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.UserId AS UserExtendedProperties_UserId, " & vbCrLf &
                "            T.KeyId AS UserExtendedProperties_KeyId, " & vbCrLf &
                "            T.[Value] AS UserExtendedProperties_Value, " & vbCrLf &
                "            T.DateCreated AS UserExtendedProperties_DateCreated, " & vbCrLf &
                "            T.DateExpired AS UserExtendedProperties_DateExpired, " & vbCrLf &
                "            T.LastChangeDate AS UserExtendedProperties_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.UserExtendedProperties AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.UserExtendedProperties.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView23() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing UserExtendedProperties" & vbCrLf &
                "        [Reference.John.Model.UserExtendedProperty](T1.UserExtendedProperty_UserId, T1.UserExtendedProperty_KeyId, T1.UserExtendedProperty_Value, T1.UserExtendedProperty_DateCreated, T1.UserExtendedProperty_DateExpired, T1.UserExtendedProperty_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.UserId AS UserExtendedProperty_UserId, " & vbCrLf &
                "            T.KeyId AS UserExtendedProperty_KeyId, " & vbCrLf &
                "            T.[Value] AS UserExtendedProperty_Value, " & vbCrLf &
                "            T.DateCreated AS UserExtendedProperty_DateCreated, " & vbCrLf &
                "            T.DateExpired AS UserExtendedProperty_DateExpired, " & vbCrLf &
                "            T.LastChangeDate AS UserExtendedProperty_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.UserExtendedProperties AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.SearchResults.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView24() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing SearchResults" & vbCrLf &
                "        [Reference.John.Model.Store.SearchResults](T1.SearchResults_FormId, T1.SearchResults_FirstName, T1.SearchResults_LastName, T1.SearchResults_GenderId, T1.SearchResults_RaceId, T1.SearchResults_RegionId, T1.SearchResults_EthnicityId, T1.SearchResults_DateCreated, T1.SearchResults_LastChangeUser, T1.SearchResults_LastChangeDate, T1.SearchResults_EthnicityName, T1.SearchResults_GenderName, T1.SearchResults_ClientToken)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.FormId AS SearchResults_FormId, " & vbCrLf &
                "            T.FirstName AS SearchResults_FirstName, " & vbCrLf &
                "            T.LastName AS SearchResults_LastName, " & vbCrLf &
                "            T.GenderId AS SearchResults_GenderId, " & vbCrLf &
                "            T.RaceId AS SearchResults_RaceId, " & vbCrLf &
                "            T.RegionId AS SearchResults_RegionId, " & vbCrLf &
                "            T.EthnicityId AS SearchResults_EthnicityId, " & vbCrLf &
                "            T.DateCreated AS SearchResults_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS SearchResults_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS SearchResults_LastChangeDate, " & vbCrLf &
                "            T.EthnicityName AS SearchResults_EthnicityName, " & vbCrLf &
                "            T.GenderName AS SearchResults_GenderName, " & vbCrLf &
                "            T.ClientToken AS SearchResults_ClientToken, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.SearchResults AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.SearchResults.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView25() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing SearchResults" & vbCrLf &
                "        [Reference.John.Model.SearchResult](T1.SearchResult_FormId, T1.SearchResult_FirstName, T1.SearchResult_LastName, T1.SearchResult_GenderId, T1.SearchResult_RaceId, T1.SearchResult_RegionId, T1.SearchResult_EthnicityId, T1.SearchResult_DateCreated, T1.SearchResult_LastChangeUser, T1.SearchResult_LastChangeDate, T1.SearchResult_EthnicityName, T1.SearchResult_GenderName, T1.SearchResult_ClientToken)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.FormId AS SearchResult_FormId, " & vbCrLf &
                "            T.FirstName AS SearchResult_FirstName, " & vbCrLf &
                "            T.LastName AS SearchResult_LastName, " & vbCrLf &
                "            T.GenderId AS SearchResult_GenderId, " & vbCrLf &
                "            T.RaceId AS SearchResult_RaceId, " & vbCrLf &
                "            T.RegionId AS SearchResult_RegionId, " & vbCrLf &
                "            T.EthnicityId AS SearchResult_EthnicityId, " & vbCrLf &
                "            T.DateCreated AS SearchResult_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS SearchResult_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS SearchResult_LastChangeDate, " & vbCrLf &
                "            T.EthnicityName AS SearchResult_EthnicityName, " & vbCrLf &
                "            T.GenderName AS SearchResult_GenderName, " & vbCrLf &
                "            T.ClientToken AS SearchResult_ClientToken, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.SearchResults AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.FileStore.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView26() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing FileStore" & vbCrLf &
                "        [Reference.John.Model.Store.FileStore](T1.FileStore_FileStoreId, T1.FileStore_EntityName, T1.FileStore_EntityKey, T1.FileStore_File, T1.FileStore_ClientToken, T1.FileStore_DateCreated, T1.FileStore_LastChangeUser, T1.FileStore_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.FileStoreId AS FileStore_FileStoreId, " & vbCrLf &
                "            T.EntityName AS FileStore_EntityName, " & vbCrLf &
                "            T.EntityKey AS FileStore_EntityKey, " & vbCrLf &
                "            T.File AS FileStore_File, " & vbCrLf &
                "            T.ClientToken AS FileStore_ClientToken, " & vbCrLf &
                "            T.DateCreated AS FileStore_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS FileStore_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS FileStore_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.FileStores AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.FileStores.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView27() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing FileStores" & vbCrLf &
                "        [Reference.John.Model.FileStore](T1.FileStore_FileStoreId, T1.FileStore_EntityName, T1.FileStore_EntityKey, T1.FileStore_File, T1.FileStore_ClientToken, T1.FileStore_DateCreated, T1.FileStore_LastChangeUser, T1.FileStore_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.FileStoreId AS FileStore_FileStoreId, " & vbCrLf &
                "            T.EntityName AS FileStore_EntityName, " & vbCrLf &
                "            T.EntityKey AS FileStore_EntityKey, " & vbCrLf &
                "            T.File AS FileStore_File, " & vbCrLf &
                "            T.ClientToken AS FileStore_ClientToken, " & vbCrLf &
                "            T.DateCreated AS FileStore_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS FileStore_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS FileStore_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.FileStore AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for ReferenceJohnModelStoreContainer.AuditLog.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView28() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing AuditLog" & vbCrLf &
                "        [Reference.John.Model.Store.AuditLog](T1.AuditLog_AuditLogId, T1.AuditLog_Action, T1.AuditLog_Type, T1.AuditLog_EntityKey, T1.AuditLog_ChangeSet, T1.AuditLog_CountofFieldsModified, T1.AuditLog_DateCreated, T1.AuditLog_LastChangeUser, T1.AuditLog_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.AuditLogId AS AuditLog_AuditLogId, " & vbCrLf &
                "            T.Action AS AuditLog_Action, " & vbCrLf &
                "            T.Type AS AuditLog_Type, " & vbCrLf &
                "            T.EntityKey AS AuditLog_EntityKey, " & vbCrLf &
                "            T.ChangeSet AS AuditLog_ChangeSet, " & vbCrLf &
                "            T.CountofFieldsModified AS AuditLog_CountofFieldsModified, " & vbCrLf &
                "            T.DateCreated AS AuditLog_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS AuditLog_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS AuditLog_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM Reference_JohnEntities.AuditLogs AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for Reference_JohnEntities.AuditLogs.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView29() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing AuditLogs" & vbCrLf &
                "        [Reference.John.Model.AuditLog](T1.AuditLog_AuditLogId, T1.AuditLog_Action, T1.AuditLog_Type, T1.AuditLog_EntityKey, T1.AuditLog_ChangeSet, T1.AuditLog_CountofFieldsModified, T1.AuditLog_DateCreated, T1.AuditLog_LastChangeUser, T1.AuditLog_LastChangeDate)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.AuditLogId AS AuditLog_AuditLogId, " & vbCrLf &
                "            T.Action AS AuditLog_Action, " & vbCrLf &
                "            T.Type AS AuditLog_Type, " & vbCrLf &
                "            T.EntityKey AS AuditLog_EntityKey, " & vbCrLf &
                "            T.ChangeSet AS AuditLog_ChangeSet, " & vbCrLf &
                "            T.CountofFieldsModified AS AuditLog_CountofFieldsModified, " & vbCrLf &
                "            T.DateCreated AS AuditLog_DateCreated, " & vbCrLf &
                "            T.LastChangeUser AS AuditLog_LastChangeUser, " & vbCrLf &
                "            T.LastChangeDate AS AuditLog_LastChangeDate, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM ReferenceJohnModelStoreContainer.AuditLog AS T" & vbCrLf &
                "    ) AS T1")
        End Function
    End Class
End Namespace
