'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports Reference.John.Domain
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class Reference_JohnEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Reference_JohnEntities")
    End Sub

	''' <summary>
    ''' Custom constuctor to pass connection string name.
    ''' </summary>
    ''' <param name="connectionStringName"></param>
    ''' <remarks></remarks>
	Public Sub New(connectionStringName As String)
		 MyBase.New("name=" & connectionStringName)
	End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Addresses() As DbSet(Of Address)
    Public Overridable Property AddressTypeOptionLists() As DbSet(Of AddressTypeOptionList)
    Public Overridable Property ApplicationExtendedProperties() As DbSet(Of ApplicationExtendedProperty)
    Public Overridable Property EthnicityOptionLists() As DbSet(Of EthnicityOptionList)
    Public Overridable Property FormSimpleZeroes() As DbSet(Of FormSimpleZero)
    Public Overridable Property FormSimpleZeroHistories() As DbSet(Of FormSimpleZeroHistory)
    Public Overridable Property GenderOptionLists() As DbSet(Of GenderOptionList)
    Public Overridable Property RaceOptionLists() As DbSet(Of RaceOptionList)
    Public Overridable Property RegionOptionLists() As DbSet(Of RegionOptionList)
    Public Overridable Property UserExtendedProperties() As DbSet(Of UserExtendedProperty)
    Public Overridable Property SearchResults() As DbSet(Of SearchResult)

    Public Overridable Function GetApplicationProperty(applicationId As String, keyId As String) As ObjectResult(Of String)
        Dim applicationIdParameter As ObjectParameter = If(applicationId IsNot Nothing, New ObjectParameter("ApplicationId", applicationId), New ObjectParameter("ApplicationId", GetType(String)))

        Dim keyIdParameter As ObjectParameter = If(keyId IsNot Nothing, New ObjectParameter("KeyId", keyId), New ObjectParameter("KeyId", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("GetApplicationProperty", applicationIdParameter, keyIdParameter)
    End Function

    Public Overrides Function SaveChanges() As Integer
		ChangeTracker.DetectChanges()
        Dim context As Core.Objects.ObjectContext = DirectCast(Me, IObjectContextAdapter).ObjectContext

        'Find all Entities that are Added/Modified that implement the date interface
        Dim objectStateEntries As IEnumerable(Of Core.Objects.ObjectStateEntry) = From e In context.ObjectStateManager.GetObjectStateEntries(EntityState.Added Or EntityState.Modified)
                                                                            Where e.IsRelationship = False AndAlso e.Entity IsNot Nothing _
                                                                            AndAlso GetType(Interfaces.IEntityDates).IsAssignableFrom(e.Entity.[GetType]())

        Dim currentTime = Providers.TimeProvider.Current.UtcNow

        For Each item In objectStateEntries
            Dim entityBase = TryCast(item.Entity, Interfaces.IEntityDates)

            If item.State = EntityState.Added Then
                entityBase.DateCreated = currentTime
            End If

            entityBase.LastChangeDate = currentTime
        Next

        Return MyBase.SaveChanges()
    End Function

End Class
