'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports Reference.John.Domain

Partial Public Class Reference_JohnEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Reference_JohnEntities")
    End Sub

	''' <summary>
    ''' Custom constuctor to pass connection string name.
    ''' </summary>
    ''' <param name="connectionStringName"></param>
    ''' <remarks></remarks>
	Public Sub New(connectionStringName As String)
		 MyBase.New("name=" & connectionStringName)
	End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property EthnicityOptionLists() As DbSet(Of EthnicityOptionList)
    Public Overridable Property FormSimpleZeroes() As DbSet(Of FormSimpleZero)
    Public Overridable Property FormSimpleZeroHistories() As DbSet(Of FormSimpleZeroHistory)
    Public Overridable Property GenderOptionLists() As DbSet(Of GenderOptionList)
    Public Overridable Property RaceOptionLists() As DbSet(Of RaceOptionList)
    Public Overridable Property RegionOptionLists() As DbSet(Of RegionOptionList)
    Public Overridable Property Addresses() As DbSet(Of Address)
    Public Overridable Property AddressTypeOptionLists() As DbSet(Of AddressTypeOptionList)
    Public Overridable Property ApplicationExtendedProperties() As DbSet(Of ApplicationExtendedProperty)
    Public Overridable Property UserExtendedProperties() As DbSet(Of UserExtendedProperty)

End Class
