'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Names
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Reference.John.Resources.Names", GetType(Names).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 1.
        '''</summary>
        Public Shared ReadOnly Property AddressLine1() As String
            Get
                Return ResourceManager.GetString("AddressLine1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 2.
        '''</summary>
        Public Shared ReadOnly Property AddressLine2() As String
            Get
                Return ResourceManager.GetString("AddressLine2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Line 3.
        '''</summary>
        Public Shared ReadOnly Property AddressLine3() As String
            Get
                Return ResourceManager.GetString("AddressLine3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Type Id.
        '''</summary>
        Public Shared ReadOnly Property AddressTypeId() As String
            Get
                Return ResourceManager.GetString("AddressTypeId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Public Shared ReadOnly Property City() As String
            Get
                Return ResourceManager.GetString("City", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client Token.
        '''</summary>
        Public Shared ReadOnly Property ClientToken() As String
            Get
                Return ResourceManager.GetString("ClientToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Created.
        '''</summary>
        Public Shared ReadOnly Property DateCreated() As String
            Get
                Return ResourceManager.GetString("DateCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ethnicity.
        '''</summary>
        Public Shared ReadOnly Property EthnicityId() As String
            Get
                Return ResourceManager.GetString("EthnicityId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name.
        '''</summary>
        Public Shared ReadOnly Property FirstName() As String
            Get
                Return ResourceManager.GetString("FirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Form Simple Zero Id.
        '''</summary>
        Public Shared ReadOnly Property FormSimpleZeroId() As String
            Get
                Return ResourceManager.GetString("FormSimpleZeroId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gender.
        '''</summary>
        Public Shared ReadOnly Property GenderId() As String
            Get
                Return ResourceManager.GetString("GenderId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Id.
        '''</summary>
        Public Shared ReadOnly Property Id() As String
            Get
                Return ResourceManager.GetString("Id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Change Date.
        '''</summary>
        Public Shared ReadOnly Property LastChangeDate() As String
            Get
                Return ResourceManager.GetString("LastChangeDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Change User.
        '''</summary>
        Public Shared ReadOnly Property LastChangeUser() As String
            Get
                Return ResourceManager.GetString("LastChangeUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Name.
        '''</summary>
        Public Shared ReadOnly Property LastName() As String
            Get
                Return ResourceManager.GetString("LastName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Race.
        '''</summary>
        Public Shared ReadOnly Property RaceId() As String
            Get
                Return ResourceManager.GetString("RaceId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Region.
        '''</summary>
        Public Shared ReadOnly Property RegionId() As String
            Get
                Return ResourceManager.GetString("RegionId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Row Version.
        '''</summary>
        Public Shared ReadOnly Property RowVersion() As String
            Get
                Return ResourceManager.GetString("RowVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State.
        '''</summary>
        Public Shared ReadOnly Property State() As String
            Get
                Return ResourceManager.GetString("State", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip.
        '''</summary>
        Public Shared ReadOnly Property Zip() As String
            Get
                Return ResourceManager.GetString("Zip", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
